version: '3'
services:
  linkr:
    image: tiirex9/linkr
    depends_on:
      - mysql
    env_file: .env

  mysql:
    image: mariadb
    volumes:
      - linkr-data:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    env_file: .env

  redis:
    image: redis

volumes:
  ? linkr-data
