version: '3'
services:
  linkr:
    image: tiirex9/linkr
    depends_on:
      - mysql
    volumes:
      - ./config:/config
    #ports:
      #- 80:80
    env_file: .env

  mysql:
    image: mariadb
    volumes:
      - ./data:/var/lib/mysql
    env_file: .env
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'

  redis:
    image: redis

