version: '3'
services:
  linkr:
    image: tiirex9/linkr
    depends_on:
      - mysql
    networks:
      - default

  mysql:
    image: mariadb
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    networks:
      - default

  redis:
    image: redis
    networks:
      - default

networks:
  ? default
