version: '3'
services:
  linkr:
    build: linkr
    depends_on:
      - mysql
    volumes:
      - ./config:/config
    ports:
      - 2000:80
    env_file: .env

  mysql:
    image: mariadb
    volumes:
      - ./data:/var/lib/mysql
    env_file: .env
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'

  redis:
    image: redis

